### ISSUE TITLE
StrictMode policy violation - A resource was acquired at attached stack trace but never released

### ISSUE THREAD

**Issue by wezley98** [adobe/aepsdk-core-android#571] opened 2023-10-23 13:38 UTC
### Expected Behaviour
No strictmode error detected

### Reproduce Scenario (including but not limited to)
- Create app using adobe aepSDK.
- Start app with StrictMode enabled
```
 StrictMode.setThreadPolicy(
            StrictMode.ThreadPolicy.Builder()
                .detectDiskReads()
                .detectDiskWrites()
                .detectAll() // or .detectAll() for all detectable problems
                .penaltyLog()
                .build()
        )
        StrictMode.setVmPolicy(
            StrictMode.VmPolicy.Builder()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .penaltyDeath()
                .build()
        )
```
- Observe following error

```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                                                    	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1994)
                                                                                                    	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
                                                                                                    	at java.io.FileInputStream.finalize(FileInputStream.java:508)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
                                                                                                    	at java.lang.Daemons$Daemon.run(Daemons.java:145)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.Throwable: Explicit termination method 'close' not called
                                                                                                    	at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
                                                                                                    	at dalvik.system.CloseGuard.open(CloseGuard.java:257)
                                                                                                    	at java.io.FileInputStream.<init>(FileInputStream.java:176)
                                                                                                    	at com.adobe.marketing.mobile.services.internal.caching.FileCacheResult.getData(FileCacheResult.java:44)
                                                                                                    	at com.adobe.marketing.mobile.internal.configuration.ConfigurationDownloader.handleDownloadResponse(ConfigurationDownloader.kt:163)
                                                                                                    	at com.adobe.marketing.mobile.internal.configuration.ConfigurationDownloader.access$handleDownloadResponse(ConfigurationDownloader.kt:41)
                                                                                                    	at com.adobe.marketing.mobile.internal.configuration.ConfigurationDownloader$download$networkCallback$1.call(ConfigurationDownloader.kt:111)
                                                                                                    	at com.adobe.marketing.mobile.services.NetworkService$1.run(NetworkService.java:65)
```

#### Platform and Version
```
adobe-bom = { module = "com.adobe.marketing.mobile:sdk-bom", version = "2.5.1" }
adobe-edge = { module = "com.adobe.marketing.mobile:edge" }
adobe-media = { module = "com.adobe.marketing.mobile:media" }
adobe-assurance = { module = "com.adobe.marketing.mobile:assurance" }
adobe-edgeidentity = { module = "com.adobe.marketing.mobile:edgeidentity" }
adobe-audience = { module = "com.adobe.marketing.mobile:audience" }
adobe-analytics = { module = "com.adobe.marketing.mobile:analytics" }
adobe-userprofile = { module = "com.adobe.marketing.mobile:userprofile" }
adobe-core = { module = "com.adobe.marketing.mobile:core" }
adobe-signal = { module = "com.adobe.marketing.mobile:signal" }
adobe-lifecycle = { module = "com.adobe.marketing.mobile:lifecycle" }
```

#### Sample Code that illustrates the problem

```
    fun enable() {
        MobileCore.setApplication(applicationContext as Application)
        MobileCore.configureWithAppID(apiKey)

        val extensions: MutableList<Class<out Extension?>> = ArrayList()

        when {
            isDebug -> {
                MobileCore.setLogLevel(LoggingMode.DEBUG)
                enableDebugExts(extensions)
            }

            else -> enableReleaseExts(extensions)
        }

        MobileCore.registerExtensions(extensions) {
            Timber.d(
                "AEP Mobile SDK is initialized"
            )
        }
    }

    private fun enableDebugExts(extensions: MutableList<Class<out Extension?>>): MutableList<Class<out Extension?>> {
        with(extensions) {
            add(Assurance.EXTENSION)
            add(Edge.EXTENSION)
            add(Identity.EXTENSION)
            add(Lifecycle.EXTENSION)
        }
        return extensions
    }

    private fun enableReleaseExts(extensions: MutableList<Class<out Extension?>>): MutableList<Class<out Extension?>> {
        with(extensions) {
            add(Edge.EXTENSION)
            add(Media.EXTENSION)
            add(Identity.EXTENSION)
            add(Audience.EXTENSION)
            add(Analytics.EXTENSION)
            add(UserProfile.EXTENSION)
            add(Lifecycle.EXTENSION)
            add(Signal.EXTENSION)
        }
        return extensions
    }
}
```

#### Logs taken while reproducing problem
See Above.

**Comment by prudrabhat** [comment] 2023-10-24 00:39
@wezley98 - Thank you for reporting this issue. Based on the trace that you shared, it seems like the issue is occurring due to [StreamUtils.readString](https://github.com/adobe/aepsdk-core-android/blob/main/code/core/src/main/java/com/adobe/marketing/mobile/util/StreamUtils.java#L50) ()which is a utility method that is used during the configuration download flow) not closing the stream. I am assigning the issue to myself and will provide an update here in this conversation when I have verified it and have a fix.

Thanks,
Prashanth

**Closed** 2023-10-31 17:55 UTC
